export { default as Navbar } from "./sections/Navbar";
export { default as Hero } from "./sections/Hero";
export { default as About } from "./sections/About";
export { default as SkillsExperience } from "./sections/SkillsExperience";
export { default as Projects } from "./sections/Projects";
export { default as Contact } from "./sections/Contact";
export { default as Resume } from "./sections/Resume";
export { default as Footer } from "./sections/Footer";
export { default as AnimatedSection } from "./ui/AnimatedSection";
